# NOT an url. Plesee see http://api.zeromq.org/2-1:zmq-tcp
endpoint: tcp://127.0.0.1:198
transfer_method: logstash
logstash:
    host: 127.0.0.1
    port: 24224
remote_syslog:
    server: syslog.example.net    
    proto: udp
    port: 514
